stack_overseer/question_monitor/urls.py
"""
This is the router logic for the question_monitor application
"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.index, name="home")

]

# urls from question_monitor application
urlpatterns += [
    url(r"^$", views.HomePageView.as_view(), name="home"),
    url(r"^trending$", views.TrendingView.as_view(), name="trending"),
    url(r"^latest$", views.LatestView.as_view(), name="latest"),
    url("answers/", views.get_answer, name="get_answer"),
    url("heatmap/", views.get_heatmap, name="get_heatmap"),
    url("wordcloud/", views.get_word_cloud, name="get_word_cloud"),

]
app_name = 'question_monitor'

stack_overseer/stack_overseer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

# inject our own routers

urlpatterns += [
    path('', include('question_monitor.urls', namespace="question_monitor"))
]

stack_overseer/question_monitor/models.py
# Create your models here.

stack_overseer/question_monitor/views.py
"""
Answer to AJAX requests and normal template context handling.
This is the backend business logic of question_monitor app.
Each view provides a interface to render engine.
"""
import html
import time
from collections import Counter

from django.contrib import messages
from django.http import JsonResponse
from django.views.generic.base import TemplateView

from .config.api_config import API_KEY
from .data_extractor import Extractor
from .rss_parser import RSSExtractor

DAY = 86400  # exact epoch time for a day


class TrendingView(TemplateView):
    template_name = "question_monitor/trending.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        messages.info(self.request, "hello http://example.com")
        context['card_loop'] = range(0, 10)
        context['top_ten'] = self.extract_result_parser()
        return context

    def extract_result_parser(self):
        # logic: get 10 top voted questions over the last week.
        question_extractor = Extractor(api_key=API_KEY, request_type="search", site="stackoverflow",
                                       tagged="android", page=1, pagesize=10, sort="votes",
                                       fromdate=int(time.time()) - DAY * 7, todate=int(time.time()))
        question_json = question_extractor.extract()

        top_ten = []  # a list of top ten votes
        for each_question in question_json["items"]:
            title = html.unescape(each_question['title'])
            info_block = [str(each_question["score"]), each_question["link"], each_question["tags"],
                          title, str(each_question['question_id']), str(each_question["answer_count"])]
            top_ten.append(info_block)
        # print(top_ten)
        return top_ten


class LatestView(TemplateView):
    template_name = "question_monitor/latest.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        messages.info(self.request, "hello http://example.com")
        context['card_loop'] = range(0, 10)
        context['top_ten'] = self.extract_result_parser()
        return context

    def extract_result_parser(self):
        # logic: get 10 latest questions over the last week.
        question_extractor = Extractor(api_key=API_KEY, request_type="search", site="stackoverflow",
                                       tagged="android", page=1, pagesize=10, sort="creation")
        question_json = question_extractor.extract()

        top_ten = []  # a list of top ten votes
        for each_question in question_json["items"]:
            title = html.unescape(each_question['title'])
            info_block = [str(each_question["score"]), each_question["link"], each_question["tags"],
                          title, str(each_question['question_id']), str(each_question["answer_count"])]
            top_ten.append(info_block)
        return top_ten


def get_answer(request):
    stack_feed_json = {}
    if request.method == 'GET':
        question_id = str(request.GET.get('question_id'))
        print(question_id)
        # answer_extractor = Extractor(api_key="6pOvVEqSzJc2ki6x5q)o6w((", request_type="question_answers",
        #                              site="stackoverflow",
        #                              sort="votes", order="desc",
        #                              question_id=question_id)
        # question_json = answer_extractor.extract()

        # RSS Extractor
        stack_feed_json = RSSExtractor(question_id=question_id).parse()
    data = {'data': stack_feed_json}
    return JsonResponse(data)


def get_heatmap(request):
    """
    Handle AJAX load

    :param request:
    :return:
    """
    data = {}

    def parse_heat():
        """
        parses heat data from data source, can be modified to use db
        :return:
        """
        with open("question_monitor/static/address_book.txt", "r") as address_book:
            line = address_book.readline()
        address_list = line.split(";")
        result = []
        for each_address in address_list:
            address = each_address.split("|")
            result.append([address[0], address[1], 0.1])
        return result

    if request.method == 'GET':
        data = {'data': parse_heat()}
    return JsonResponse(data)


def get_word_cloud(request):
    """
    Handle AJAX load
    :param request:
    :return:
    """

    def parse_word_cloud():
        """parse word_cloud data from data source"""
        with open("question_monitor/static/last_week_question_tags.txt", "r") as tag_book:
            line = tag_book.readline()
        tag_list = line.split(";")
        result = list(Counter(tag_list).items())

        return result

    data = {}

    if request.method == 'GET':
        data = {'data': parse_word_cloud()}
    return JsonResponse(data)


class HomePageView(TemplateView):
    template_name = "question_monitor/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

stack_overseer/templates/question_monitor/base.html
{% load leaflet_tags %}
{% load bootstrap4 %}

{% load static %}

<!-- here we load the core js files via cdn -->
<!-- Bootstrap core JavaScript-->
<script src=" {% static 'vendor/jquery.min.js' %} "></script>
<script src=" {% static 'vendor/bootstrap.bundle.min.js' %} "></script>


<head>


<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Dashboard</title>

    <!-- Project icon& font dependency -->
    <script src="https://kit.fontawesome.com/6edeb81e55.js" crossorigin="anonymous"></script>
    <link href=" {% static 'vendor/all.min.css' %} " rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom site style-->
    <link href=" {% static 'question_monitor.css' %} " rel="stylesheet">

</head>

<!-- from here we mount the UI-base including side-nav-topbar -- >
{% block ui_base %}{% endblock %}

stack_overseer/templates/question_monitor/charts.html
{% load bootstrap4 %}
{% load static %}
<!-- Begin Page Content -->
<div class="container-fluid" id="home-container">

    <div class="row">

        <div class="col-xl-8 col-lg-7">


            <div class="card shadow mb-4" id="chart-card">
                <div class="card-header py-3">
                    <h2 class="m-0 font-weight-bold text-primary">Dashboard</h2>
                </div>
                <div class="card-body">
                    <div class="chart-area">

                        {% include "question_monitor/leaflet.html" %}
                        <hr>
                        <p> Wondering where <strong>Android</strong> questions are coming from? (Past week)</p>
                        <hr>
                        <canvas width="1550px" height="315rem"
                                id="word-cloud-canvas"></canvas>
                        <hr>
                        A word-cloud demonstrating the most related tags to <strong>Android</strong> over the past week.
                    </div>

                </div>
            </div>


        </div>
    </div>

</div>


<script src="https://cdn.bootcss.com/wordcloud2.js/1.1.0/wordcloud2.js"></script>

<script>

    $.get(location.origin + '/wordcloud/',
        function (data) {

            var options = eval({
                "list": data.data,
                "shape": "circle",
                "gridSize": 13, // size of the grid in pixels
                "weightFactor": 0.4, // number to multiply for size of each word in the list
                "fontWeight": 'bold', // 'normal', 'bold' or a callback
                "fontFamily": 'Times, serif', // font to use
                "color": 'random-light', // 'random-dark' or 'random-light'
                "backgroundColor": '#333', // the color of canvas
                "rotateRatio": 1 // probability for the word to rotate. 1 means always rotate
            });
            var canvas = document.getElementById('word-cloud-canvas');

            WordCloud(canvas, options);
        });


</script>

stack_overseer/templates/question_monitor/home.html
{% extends 'question_monitor/ui_base.html' %}
{% load bootstrap4 %}
{% load static %}


<!-- Here we inject the non UI part in each html template page -->
{% block main %}

    <!-- Essential css -->
    <link href=" {% static 'question.css' %} " rel="stylesheet" type="text/css">

    <!-- chart content Starts here -->

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- chart content ends here -->

        {% include "question_monitor/charts.html" %}


    </div>






{% endblock %}

stack_overseer/templates/question_monitor/latest.html
{% extends 'question_monitor/ui_base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load index %}

<!-- Here we inject the non UI part in each html template page -->
{% block main %}

    <link href=" {% static 'question.css' %} " rel="stylesheet" type="text/css">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading with a refresh button-->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Latest Questions on <strong>Android</strong> (Real Time) </h1>
            <button onClick="window.location.reload();" class="btn btn-primary"><span
                    class="glyphicon glyphicon-refresh"></span> Refresh
            </button>
        </div>

        <div class="row">
            {% for i in card_loop %}

                <!-- Now we have 10 boxes of identical size and style, ready to inject data -->

                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters ">
                                <div class="col mr-2 stats">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Votes
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ top_ten|index:forloop.counter0|index:0 }}</div>
                                    </div>
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Answers
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ top_ten|index:forloop.counter0|index:5 }}</div>
                                    </div>

                                    <a href="{{ top_ten|index:forloop.counter0|index:1 }}" target="_blank"
                                       title="Click here to StackOverflow"> <i class="fas fa-link fa-2x "></i></a>

                                </div>

                                <div class="col-auto q-title">
                                    <a data-toggle="modal"
                                       data-target="#exampleModalLong{{ top_ten|index:forloop.counter0|index:4 }}">

                                        <h2 id="clickable-title">
                                            <small>
                                                {{ top_ten|index:forloop.counter0|index:3 }}

                                                <div id="question_id"
                                                     hidden>{{ top_ten|index:forloop.counter0|index:4 }}</div>
                                            </small>
                                        </h2>
                                    </a>


                                </div>
                            </div>
                        </div>


                    </div>

                </div>
                <!-- Modal -->

                <div class="modal fade" id="exampleModalLong{{ top_ten|index:forloop.counter0|index:4 }}" tabindex="-1"
                     role="dialog"
                     aria-labelledby="exampleModalLongTitle" aria-hidden="true">

                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Q&A</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="rss-response" id="rss{{ top_ten|index:forloop.counter0|index:4 }}">

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary">Vote this question!</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <script type="text/javascript">
                    var question_id = "{{ top_ten|index:forloop.counter0|index:4}}";

                    $('#exampleModalLong{{ top_ten|index:forloop.counter0|index:4 }}').on('shown.bs.modal', function (e) {
                        e.preventDefault();
                        var question_id = "{{ top_ten|index:forloop.counter0|index:4}}";
                        $.get(location.origin + '/answers/',
                            {'question_id': question_id},
                            function (data) {
                                console.log(data.data.items[0][0]);
                                console.log(data.data.items.length);
                                let html_base = [];
                                html_base.push("<div id='modal-data-wrap'>" +
                                    "<i id='question-icon' class='fas fa-question question-icon'></i>" +
                                    "<div>" + data.data.items[0][0] + "</div>" +
                                    "<div>" + data.data.items[0][1] + "</div>" +
                                    "<div>" + data.data.items[0][2] + "</div>" + "</div>")
                                for (let e = 1; e < data.data.items.length; e++) {

                                    html_base.push("<div id='modal-data-wrap'>" +
                                        "<div>" + data.data.items[e][0] + "</div>" +
                                        "<div>" + data.data.items[e][1] + "</div>" +
                                        "<div>" + data.data.items[e][2] + "</div>" + "</div>")

                                    {% comment %}                         $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').append("<div>" + data.data.items[e][0] + "</div>");
                                                             $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').append("<div>" + data.data.items[e][1] + "</div>");
                                                             $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').append("<div>" + data.data.items[e][2] + "</div>");
                                                             $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').append("<div>--------------------------</div>");
                                                             $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').append("<div>--------------------------</div>");{% endcomment %}

                                }
                                $('#rss{{ top_ten|index:forloop.counter0|index:4 }}').html(html_base.join(""))


                            }
                        );
                    });
                </script>
            {% endfor %}
        </div>
    </div>


    {##}
        {#               <script type="text/javascript">#}
        {#                            $('#exampleModalLong63342557').on('shown.bs.modal', function (e) {#}
        {#                                e.preventDefault();#}
        {#                                var question_id = "63342557";#}
        {#                                $.get(location.origin + '/answers/',#}
        {#                                    {'question_id': question_id},#}
        {#                                    function (response) {#}
        {##}
        {#                                        $('#response_msg').text(response.msg);#}
        {#                                    }#}
        {#                                );#}
        {#                            });#}
        {#                        </script>#}









{% endblock %}

stack_overseer/templates/question_monitor/leaflet.html
{% load static %}

{% load leaflet_tags %}

{% leaflet_js plugins="heat" %}
{% leaflet_css %}
<!-- Here we initialize a heatmap object -->

{% leaflet_map "stackoverflow_hotspot" callback="window.map_init_basic" %}


<script>

    window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        $.get(location.origin + '/heatmap/',
            function (data) {
                var heat = L.heatLayer(
                    data.data
                    , {radius: 35}, {blur: 4}).addTo(map);

            })
    });
</script>

stack_overseer/templates/question_monitor/modal.html
{% load static %}
{% load index %}

<!-- getting ajax response from backend - get answers from RSS feed -->

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Q&A</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="rss-response">
                    {{ forloop.counter0 }}
                    {{ top_ten|index:forloop.counter0|index:4 }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Vote this question!</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal ends here! -->

stack_overseer/templates/question_monitor/ui_base.html
{% extends 'question_monitor/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block ui_base %}



    <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center"
               href=" {% url "question_monitor:home" %} ">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fab fa-stack-overflow"></i>
                </div>
                <div class="sidebar-brand-text mx-3">StackOverseer Dashboard</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url "question_monitor:home" %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Tools
            </div>

            <!-- Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-book"></i>
                    <span>StackExtractor</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Views</h6>
                        <a class="collapse-item" href=" {% url 'question_monitor:trending' %} ">Trending Questions</a>
                        <a class="collapse-item" href=" {% url 'question_monitor:latest' %} ">Latest Questions</a>

                    </div>
                </div>

            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Icon (Github page) -->
            <div class="text-center d-none d-md-inline">
                <i class="fas fa-info-circle fa-lg" title="Source code"
                   onclick="window.open('https://github.com/Superskyyy/StackOverseer', '_blank')"></i>
            </div>

        </ul> <!-- end of sidebar!!!!!!!!!! -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search Not implemented. -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small"
                                   placeholder="Not implemented..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>


                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Sample User</span>
                                <img class="img-profile rounded-circle"
                                     src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRcNtzzwyrwF0sVZiK0_JCyenNwFeNPy8013w&usqp=CAU">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout(Fake)
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Here we inject the actual logic UI part in each html page -->
                {% block main %} This is a bug if this line shows!!!! {% endblock %}
            </div>
        </div>

    </div>
    </body>
{% endblock %}